[package]
name = "tiles"
version = "0.1.0"
description = "Tomorrowland tiles program."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tiles"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "1.0"
libm = "0.2"
h3o = { version = "0.7", default-features = false, features = ["std"] }
